language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
script: mvn -B -V --settings target/travis-settings/settings.xml verify
after_success:
- '[[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]] || [[ $TRAVIS_TAG
  == release-* ]] && mvn -DskipTests=true -B -V --errors deploy --settings target/travis-settings/settings.xml'
env:
  global:
  - secure: bpcjm0DqW8ZMbPEUcKFO9IGctgSsC7ZSVMi/GsQS+BEbn0HiOlPNotw4oF7AZqeGv/RJ+0neaXawC1+JNTWRd0nNmL5UFG7FU5Gg0WUCfujYKGk1+bK0jaEd7a6o8+vYvciN1M53s5EIAoWIQCbzTAa0cSer/iB6lic8yFpSex27bHTTNMOH+c8hkYISvRBrPLdbwpze47WMXF/oyBnGdGK/xeZN6KSIv6QweyW1XUYC8IFTp0htVj2XlDtRl1UQSpXQ++kXCMiOwLCA7iVzldhtHS8Ar01UaivZGZCK6HIdk4GYcc3UcUdWmKcRJkzdDZ/xwvbKyAUi2Nu0ImMdIOb49kStHMPLdhWGctmccx2fRto/kNLM9Wcilp6Ianwq8Vl1p2KJuKczA9Nn3AvvbxSJPMlna36UPxgc8rdY7ryEa/L3LTVfqKZKyl/EtyICSGHTXv01GOydosisYWfbBBuYKWALbv+md0jFGdmGEYFTDKwmg7LsObTo0ST6LqoCNrCRW7ktrrkZ9Ew06ysL/lkZifGOVAGEodmEWzdsOe9Hf2QQjseyWHT7GVNHUhLALITrGrkioBGKW8qqtViqa+qTOMkghdal6O7P67na/XbNt0Js6kl/hktnke0TBWdEOps/2g7Tj2Onkw2/lqZMuZvkO3IeglF4LZnqe2QIirM=
  - secure: duTUqMoE2vrR45/r10idfUg9B2kS8d1AAEO9tXWQyO5Ix+abjuYb2EXrS0Ffzd7d4P4FeOKct86vs3fmHggEoLnZzvn6nYcsjip6/LUTj3MnLSVjwAefEZv7GMHTl4gQJdA2OLVOEFDtlg6RVK1ebW1yp86Jggkco8rZV9x5dYTix3/jW83GjfPI3a/OEqDOvjqmaXSh6/I/EWzMc8yEMYgtklCxYobZ8kNT3hQdkbYdDqWgTZVZ3C2gGjoRk57E7fzCbSRuPSLhKuEPcjFJppmLAsfALxKVYNHonn9lcIDAyX1Qaq3/ZuwEar6qKZevsswhpP9q+cF2rAnWwi0s3d3QJcvRqWa+EyIMe5PPrdzNTS9KiXxdWcK0ntGZMhSsVfmyqlSh31aq7LpujeuW04iS2o86pz8A1yZeIauv9dLdzXvpusKeT6CsoLBYce5/wUzpBZNomCKckYAh3OC4nNEtpuInIcLAAJV4Ccfi4M/k3CBdL42tHS3FA6mMLiCXJ3jBWx/e9u4BND4GRGexup/2cZyIEFX5t04HdCcK/ZNrV74EKsIXZCXCoWkvI0kviXttiCqt7JPcAVA7hbpqvTMTVCRmYG1M9Iq43AJ11fTqPXMs9rKJXmHOeS9rP5RwgMuXWCbDvzui9MFChM6fq+3k2T6M53hZHGmJQS4rZmM=
